// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: basket.proto

package basket_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBasketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasketRequest) Reset() {
	*x = GetBasketRequest{}
	mi := &file_basket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketRequest) ProtoMessage() {}

func (x *GetBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketRequest.ProtoReflect.Descriptor instead.
func (*GetBasketRequest) Descriptor() ([]byte, []int) {
	return file_basket_proto_rawDescGZIP(), []int{0}
}

func (x *GetBasketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BasketItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Quantity      string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasketItem) Reset() {
	*x = BasketItem{}
	mi := &file_basket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketItem) ProtoMessage() {}

func (x *BasketItem) ProtoReflect() protoreflect.Message {
	mi := &file_basket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketItem.ProtoReflect.Descriptor instead.
func (*BasketItem) Descriptor() ([]byte, []int) {
	return file_basket_proto_rawDescGZIP(), []int{1}
}

func (x *BasketItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BasketItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *BasketItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *BasketItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *BasketItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *BasketItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBasketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPrice    string                 `protobuf:"bytes,1,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Items         []*BasketItem          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBasketResponse) Reset() {
	*x = GetBasketResponse{}
	mi := &file_basket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBasketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketResponse) ProtoMessage() {}

func (x *GetBasketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketResponse.ProtoReflect.Descriptor instead.
func (*GetBasketResponse) Descriptor() ([]byte, []int) {
	return file_basket_proto_rawDescGZIP(), []int{2}
}

func (x *GetBasketResponse) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

func (x *GetBasketResponse) GetItems() []*BasketItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_basket_proto protoreflect.FileDescriptor

const file_basket_proto_rawDesc = "" +
	"\n" +
	"\fbasket.proto\x12\x06basket\"\"\n" +
	"\x10GetBasketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa2\x01\n" +
	"\n" +
	"BasketItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"^\n" +
	"\x11GetBasketResponse\x12\x1f\n" +
	"\vtotal_price\x18\x01 \x01(\tR\n" +
	"totalPrice\x12(\n" +
	"\x05items\x18\x02 \x03(\v2\x12.basket.BasketItemR\x05items2Q\n" +
	"\rBasketService\x12@\n" +
	"\tGetBasket\x12\x18.basket.GetBasketRequest\x1a\x19.basket.GetBasketResponseB\vZ\tbasket.v1b\x06proto3"

var (
	file_basket_proto_rawDescOnce sync.Once
	file_basket_proto_rawDescData []byte
)

func file_basket_proto_rawDescGZIP() []byte {
	file_basket_proto_rawDescOnce.Do(func() {
		file_basket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basket_proto_rawDesc), len(file_basket_proto_rawDesc)))
	})
	return file_basket_proto_rawDescData
}

var file_basket_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_basket_proto_goTypes = []any{
	(*GetBasketRequest)(nil),  // 0: basket.GetBasketRequest
	(*BasketItem)(nil),        // 1: basket.BasketItem
	(*GetBasketResponse)(nil), // 2: basket.GetBasketResponse
}
var file_basket_proto_depIdxs = []int32{
	1, // 0: basket.GetBasketResponse.items:type_name -> basket.BasketItem
	0, // 1: basket.BasketService.GetBasket:input_type -> basket.GetBasketRequest
	2, // 2: basket.BasketService.GetBasket:output_type -> basket.GetBasketResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_basket_proto_init() }
func file_basket_proto_init() {
	if File_basket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basket_proto_rawDesc), len(file_basket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basket_proto_goTypes,
		DependencyIndexes: file_basket_proto_depIdxs,
		MessageInfos:      file_basket_proto_msgTypes,
	}.Build()
	File_basket_proto = out.File
	file_basket_proto_goTypes = nil
	file_basket_proto_depIdxs = nil
}
